[package]
name = "dagger"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Lattice task dependency graph builder and scheduler"

[dependencies]
lattice-config = { path = "../lattice-config" }
lattice-workspace = { path = "../lattice-workspace" }
anyhow = "1"
petgraph = "0.6"

[dev-dependencies]
indexmap = "2"
