[workspace]
members = [
    "crates/lattice",
    "crates/lattice-cache",
    "crates/lattice-config",
    "crates/dagger",
    "crates/lattice-output",
    "crates/lattice-runner",
    "crates/lattice-workspace",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ryan Mullin"]
license = "ISC"
