[package]
name = "lattice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Local-first, language-agnostic monorepo build tool"

[[bin]]
name = "lattice"
path = "src/main.rs"

[dependencies]
lattice-config = { path = "../lattice-config" }
dagger = { path = "../dagger" }
lattice-output = { path = "../lattice-output" }
lattice-runner = { path = "../lattice-runner" }
lattice-workspace = { path = "../lattice-workspace" }
lattice-cache = { path = "../lattice-cache" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
console = "0.15"
dialoguer = "0.11"
serde_json = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
